name: Publish Package

on:
  push:
    tags:
      - 'v*' # 推送带有 v 开头的标签时触发，例如 v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # 可以根据你的项目需要选择 Python 的版本
      
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install dependencies
      run: uv sync
      
    - name: Build package
      run: uv build
      
    - name: Publish package to PyPI
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: uv publish
